### ISSUE TITLE
java.lang.OutOfMemoryError: Requested array size exceeds VM limit on Travis CI

### ISSUE THREAD

**Issue by rmatil** [p2p-sync/network#3]
Commit p2p-sync/network@4743b64 is causing the following error on Travis CI

```
org.rmatil.sync.network.test.core.model.ClientLocationTest  Time elapsed: 0.037 sec  <<< ERROR!
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:54)
    at io.netty.util.concurrent.DefaultEventExecutorGroup.<init>(DefaultEventExecutorGroup.java:40)
    at io.netty.util.concurrent.DefaultEventExecutorGroup.<init>(DefaultEventExecutorGroup.java:30)
    at org.rmatil.sync.network.core.Client.initPeerDht(Client.java:242)
    at org.rmatil.sync.network.core.Client.start(Client.java:68)
    at org.rmatil.sync.network.test.core.model.ClientLocationTest.setUp(ClientLocationTest.java:44)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by rmatil** [comment]
> This is (of course) totally VM-dependent.
> Browsing through the source code of OpenJDK 7 and 8 java.util.ArrayList,
> .Hashtable, .AbstractCollection,  .PriorityQueue, and .Vector, you can see this claim being repeated:
> 
> ``` java
> /* Some VMs **reserve some header words in an array.**  
>  * Attempts to allocate larger arrays may result in
>  * OutOfMemoryError: Requested array size exceeds VM limit
> */
> 
> private static final int MAX_ARRAY_SIZE = Integer.MAX_VALUE - 8;
> ```
> 
> which is added by Martin Buchholz (Google) on 2010-05-09; reviewed by Chris 
> Hegarty (Oracle).
> 
> So, probably we can say that the maximum "safe" number would be 2 147 483 639 
> (Integer.MAX_VALUE - 8) and "attempts to allocate larger arrays may result in 
> OutOfMemoryError".
> 
> (Yes, Buchholz's standalone claim does not include backing evidence, so this is a
> calculated appeal to authority. Even within OpenJDK itself, we can see code like 
> return (minCapacity > MAX_ARRAY_SIZE) ? Integer.MAX_VALUE : 
> MAX_ARRAY_SIZE; which shows that MAX_ARRAY_SIZE does not yet have a 
> real use.)
> 
> -- <cite>http://stackoverflow.com/a/8381338</cite>

**Comment by rmatil** [comment]
Note, that the maximum limit of Threads for a process on OS X 10.11 is limited to 2048. When trying to create a new native thread, then the following exception is thrown:

```
[ERROR] [Slf4JLogger.java:181]: Failed to submit a listener notification task. Event loop shut down?
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:714)
    at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:217)
    at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:210)
    at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
    at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:641)
    at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138)
    at io.netty.channel.group.DefaultChannelGroupFuture.addListener(DefaultChannelGroupFuture.java:152)
    at io.netty.channel.group.DefaultChannelGroupFuture.addListener(DefaultChannelGroupFuture.java:40)
    at net.tomp2p.connection.ChannelCreator.shutdown(ChannelCreator.java:334)
    at net.tomp2p.utils.Utils$4$1.operationComplete(Utils.java:820)
    at net.tomp2p.utils.Utils$4$1.operationComplete(Utils.java:816)
    at net.tomp2p.futures.BaseFutureImpl.callOperationComplete(BaseFutureImpl.java:328)
    at net.tomp2p.futures.BaseFutureImpl.addListener(BaseFutureImpl.java:314)
    at net.tomp2p.utils.Utils$4.operationComplete(Utils.java:816)
    at net.tomp2p.futures.BaseFutureImpl.callOperationComplete(BaseFutureImpl.java:328)
    at net.tomp2p.futures.BaseFutureImpl.notifyListeners(BaseFutureImpl.java:361)
    at net.tomp2p.futures.BaseFutureImpl.failed(BaseFutureImpl.java:232)
    at net.tomp2p.futures.BaseFutureImpl.failed(BaseFutureImpl.java:194)
    at net.tomp2p.p2p.builder.PingBuilder$4.operationComplete(PingBuilder.java:239)
    at net.tomp2p.p2p.builder.PingBuilder$4.operationComplete(PingBuilder.java:233)
    at net.tomp2p.futures.BaseFutureImpl.callOperationComplete(BaseFutureImpl.java:328)
    at net.tomp2p.futures.BaseFutureImpl.notifyListeners(BaseFutureImpl.java:361)
    at net.tomp2p.futures.BaseFutureImpl.failed(BaseFutureImpl.java:232)
    at net.tomp2p.connection.Sender$7.operationComplete(Sender.java:796)
    at net.tomp2p.connection.Sender$7.operationComplete(Sender.java:787)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:801)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(AbstractChannel.java:784)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:466)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
    at io.netty.channel.ChannelDuplexHandler.bind(ChannelDuplexHandler.java:38)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
    at io.netty.channel.ChannelDuplexHandler.bind(ChannelDuplexHandler.java:38)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
    at io.netty.channel.ChannelOutboundHandlerAdapter.bind(ChannelOutboundHandlerAdapter.java:35)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```
